class EnvironmentSettings:
    def __init__(self):
        self.workspace_dir = '/home/ivl5/hiptrack/HIPTrack'    # Base directory for saving network checkpoints.
        self.tensorboard_dir = '/home/ivl5/hiptrack/HIPTrack/tensorboard'    # Directory for tensorboard files.
        self.pretrained_networks = '/home/ivl5/hiptrack/HIPTrack/pretrained_networks'
        self.lasot_dir = '/home/ivl5/hiptrack/HIPTrack/data/lasot'
        self.got10k_dir = '/home/ivl5/hiptrack/HIPTrack/data/got10k'
        self.got10k_val_dir = '/home/ivl5/hiptrack/HIPTrack/data/got10k/val'
        self.lasot_lmdb_dir = '/home/ivl5/hiptrack/HIPTrack/data/lasot_lmdb'
        self.got10k_lmdb_dir = '/home/ivl5/hiptrack/HIPTrack/data/got10k_lmdb'
        self.trackingnet_dir = '/home/ivl5/hiptrack/HIPTrack/data/trackingnet'
        self.trackingnet_lmdb_dir = '/home/ivl5/hiptrack/HIPTrack/data/trackingnet_lmdb'
        self.coco_dir = '/home/ivl5/hiptrack/HIPTrack/data/coco'
        self.coco_lmdb_dir = '/home/ivl5/hiptrack/HIPTrack/data/coco_lmdb'
        self.lvis_dir = ''
        self.sbd_dir = ''
        self.imagenet_dir = '/home/ivl5/hiptrack/HIPTrack/data/vid'
        self.imagenet_lmdb_dir = '/home/ivl5/hiptrack/HIPTrack/data/vid_lmdb'
        self.imagenetdet_dir = ''
        self.ecssd_dir = ''
        self.hkuis_dir = ''
        self.msra10k_dir = ''
        self.davis_dir = ''
        self.youtubevos_dir = ''
        self.mvtd_dir = '/home/ivl5/hiptrack/HIPTrack/data/mvtd/train'
